title: Damon Luck
description: Damon Luck Blog

url: https://damonluck.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: damonluck
   linkedin: damonluck
